class_name Policies

extends Node

static var available = [{'name': 'Waste Segregation Program', 'description': 'Implement a city-wide program for separating recyclable, organic, and general waste. ROI comes from selling segregated recyclable materials, reduced landfill fees, and potential subsidies for recycling programs.', 'sector': 'Waste', 'emission reduction': '30,000', 'cost': '$1,500,000', 'roi': '50,000', 'visual': 'Segregated waste bins', 'card image': 'III_1', },
{'name': 'Composting Facilities', 'description': 'Establish local composting facilities for organic waste from households and businesses. ROI is generated from selling the compost produced, reducing landfill costs, and possibly receiving organic waste processing fees.', 'sector': 'Waste', 'emission reduction': '12,000', 'cost': '$500,000', 'roi': '50,000', 'visual': 'Community compost sites', 'card image': 'III_2', },
{'name': 'Recycling Incentive Program', 'description': 'Provide incentives for households and businesses to increase recycling rates.', 'sector': 'Waste', 'emission reduction': '8,000', 'cost': '$300,000', 'roi': '0', 'visual': 'Branded recycling bins', 'card image': 'III_3', },
{'name': 'Waste-to-Energy Plant', 'description': 'Construct a plant to convert non-recyclable waste into energy. ROI comes from selling the generated energy (electricity or heat), receiving tipping fees for waste processing, and avoiding landfill costs.', 'sector': 'Waste', 'emission reduction': '30,000', 'cost': '$3,000,000', 'roi': '600,000', 'visual': 'Industrial facility', 'card image': 'III_4', },
{'name': 'Public Awareness Campaign', 'description': 'Launch a campaign to educate citizens about waste reduction and proper disposal methods.', 'sector': 'Waste', 'emission reduction': '6,000', 'cost': '$200,000', 'roi': '0', 'visual': 'Media and ads', 'card image': 'III_5', },
{'name': 'Plastic Bag Ban', 'description': 'Implement a ban on single-use plastic bags and promote alternatives.', 'sector': 'Waste', 'emission reduction': '4,000', 'cost': '$100,000', 'roi': '0', 'visual': 'Signage and posters', 'card image': 'III_6', },
{'name': 'E-Waste Collection Points', 'description': 'Set up designated points for the collection and proper disposal of electronic waste. ROI is generated from selling recovered valuable materials from e-waste, reducing hazardous waste management costs, and possibly receiving e-waste recycling fees.', 'sector': 'Waste', 'emission reduction': '8,000', 'cost': '$500,000', 'roi': '15,000', 'visual': 'Collection centers', 'card image': 'III_7', },
{'name': 'Landfill Gas Capture', 'description': 'Install systems to capture and utilize methane emissions from landfills. ROI is derived from selling captured methane as a fuel or generating electricity from it, and reducing greenhouse gas emissions penalties.', 'sector': 'Waste', 'emission reduction': '25,000', 'cost': '$2,000,000', 'roi': '100,000', 'visual': 'Industrial equipment', 'card image': 'III_8', },
{'name': 'Repair and Reuse Centers', 'description': 'Establish centers where residents can repair and donate items for reuse instead of discarding. ROI comes from reduced waste disposal costs, selling repaired or refurbished items, and promoting a circular economy.', 'sector': 'Waste', 'emission reduction': '2,000', 'cost': '$600,000', 'roi': '50,000', 'visual': 'Community centers', 'card image': 'III_9', },
{'name': 'Gov Building Renewable Energy Retrofitting', 'description': 'Program that retrofits government buildings with renewable energy sources (solar, wind). ROI comes from reduced energy bills and potential energy sales back to the grid.', 'sector': 'Energy', 'emission reduction': '20,000', 'cost': '$500,000', 'roi': '50,000', 'visual': 'Solar panels and wind turbines on government buildings', 'card image': 'I_1', },
{'name': 'Gov Building Energy Management System', 'description': 'Installing a centralized energy management system to help government buildings be more efficient in their energy usage. ROI comes from reduced energy consumption and operational savings.', 'sector': 'Energy', 'emission reduction': '15,000', 'cost': '$150,000', 'roi': '50,000', 'visual': 'Centralized energy control systems', 'card image': 'I_2', },
{'name': 'Gov LED Street Lighting Project', 'description': 'Replace regular street lights with LED lights.', 'sector': 'Energy', 'emission reduction': '10,000', 'cost': '$550,000', 'roi': '0', 'visual': 'LED street lights', 'card image': 'I_3', },
{'name': 'Residential Heat Pump Transition', 'description': 'Program that provides incentives to residential households to swap old heating/cooling systems for energy-efficient heat pumps.', 'sector': 'Energy', 'emission reduction': '25,000', 'cost': '$1,000,000', 'roi': '0', 'visual': 'Modern heat pump systems', 'card image': 'I_4', },
{'name': 'Residential Solar Water Heaters', 'description': 'Incentives for residential households to install a solar water heating system and migrate away from gas and electric water heaters.', 'sector': 'Energy', 'emission reduction': '10,000', 'cost': '$1,000,000', 'roi': '0', 'visual': 'Solar water heaters', 'card image': 'I_5', },
{'name': 'Residential Insulation Upgrades', 'description': 'Program that supports residential homeowners to insulate their homes to become more energy efficient. ROI comes from lower energy bills and increased property values.', 'sector': 'Energy', 'emission reduction': '12,000', 'cost': '$1,000,000', 'roi': '30,000', 'visual': 'Improved home insulation', 'card image': 'I_6', },
{'name': 'Residential Renewable Energy Program', 'description': 'Subsidizing residential solar panels or wind turbines for homeowners and multifamily housing (apartments), which also results in incentives like tax breaks and lower costs of energy.', 'sector': 'Energy', 'emission reduction': '35,000', 'cost': '$2,000,000', 'roi': '0', 'visual': 'Solar panels and wind turbines on residential properties', 'card image': 'I_7', },
{'name': 'Residential Renewable Energy Education Program', 'description': 'Educational outreach project to educate and train the populace on renewable energy technologies, energy efficiency practices, and available programs.', 'sector': 'Energy', 'emission reduction': '5,000', 'cost': '$125,000', 'roi': '0', 'visual': 'Educational materials and workshops', 'card image': 'I_8', },
{'name': 'Commercial Green Building Standards Subsidies', 'description': 'Subsidies to meet standards and tax incentives and/or other incentives to encourage meeting and maintaining green building standards accreditations.', 'sector': 'Energy', 'emission reduction': '20,000', 'cost': '$2,000,000', 'roi': '0', 'visual': 'Green building certifications', 'card image': 'I_9', },
{'name': 'Commercial Energy Audit', 'description': 'Offer free or subsidized energy audits to identify areas for energy savings in commercial buildings.', 'sector': 'Energy', 'emission reduction': '15,000', 'cost': '$350,000', 'roi': '0', 'visual': 'Energy audit reports', 'card image': 'I_10', },
{'name': 'Residential and Commercial Demand Response Program', 'description': 'Incentives (and disincentives) to encourage off-peak time energy usage to reduce strain on the grid (time of use tariffs, subsidized energy, etc.).', 'sector': 'Energy', 'emission reduction': '10,000', 'cost': '$1,000,000', 'roi': '0', 'visual': 'Demand response systems', 'card image': 'I_11', },
{'name': 'Renewable Energy Power Plant', 'description': 'Install solar power and/or wind turbines. ROI comes from selling generated energy and potential energy sales back to the grid.', 'sector': 'Energy', 'emission reduction': '50,000', 'cost': '$5,000,000', 'roi': '500,000', 'visual': 'Solar power plants and wind farms', 'card image': 'I_12', },
{'name': 'Energy Storage System', 'description': 'Invest in battery storage systems to store excess renewable energy for use during peak demand in municipal buildings. ROI comes from better energy management and reduced energy costs.', 'sector': 'Energy', 'emission reduction': '30,000', 'cost': '$3,000,000', 'roi': '100,000', 'visual': 'Battery storage systems', 'card image': 'I_13', },
{'name': 'Electric Bus Fleet', 'description': 'Introduce electric buses to replace diesel buses, reducing emissions and operating costs.', 'sector': 'Transport', 'emission reduction': '20,000', 'cost': '2,500,000', 'roi': '0', 'visual': 'Bus stops with electric bus signs', 'card image': 'II_1', },
{'name': 'Carpool/Car Sharing Incentives', 'description': 'Encourage carpooling and car sharing to reduce the number of vehicles on the road.', 'sector': 'Transport', 'emission reduction': '15,000', 'cost': '1,500,000', 'roi': '0', 'visual': 'No visible impact', 'card image': 'II_2', },
{'name': 'Smart Traffic Lights and Sensors', 'description': 'Optimize traffic flow using smart traffic lights and sensors, reducing congestion and emissions.', 'sector': 'Transport', 'emission reduction': '25,000', 'cost': '1,000,000', 'roi': '0', 'visual': 'No change', 'card image': 'II_3', },
{'name': 'Public Transport Upgrade', 'description': 'Improve the quality and efficiency of public transport, encouraging more people to use it. ROI comes from increased ridership and fare revenue.', 'sector': 'Transport', 'emission reduction': '15,000', 'cost': '1,500,000', 'roi': '60,000', 'visual': 'Modernized public transport facilities', 'card image': 'II_4', },
{'name': 'Pedestrian Zones', 'description': 'Create pedestrian areas to encourage walking and reduce vehicle use. ROI comes from increased foot traffic to businesses and improved air quality.', 'sector': 'Transport', 'emission reduction': '5,000', 'cost': '750,000', 'roi': '0', 'visual': 'New pedestrian zones with signs', 'card image': 'II_5', },
{'name': 'Bike Sharing Program', 'description': 'Implement a bike-sharing program to reduce car usage. ROI comes from membership fees and reduced vehicle emissions.', 'sector': 'Transport', 'emission reduction': '7,000', 'cost': '500,000', 'roi': '10,000', 'visual': 'Bike stations', 'card image': 'II_6', },
{'name': 'Public Awareness Campaign', 'description': 'Launch a campaign to raise awareness about emission reduction in transport.', 'sector': 'Transport', 'emission reduction': '5,000', 'cost': '200,000', 'roi': '0', 'visual': 'No change', 'card image': 'II_7', },
{'name': 'Electric Scooter Fleet', 'description': 'Introduce electric scooters for short-distance travel, reducing car usage. ROI comes from rental fees and reduced emissions.', 'sector': 'Transport', 'emission reduction': '15,000', 'cost': '1,000,000', 'roi': '10,000', 'visual': 'Scooter stations around the city', 'card image': 'II_8', },
{'name': 'Commuter Rail Expansion', 'description': 'Expand the commuter rail network to connect suburban areas.', 'sector': 'Transport', 'emission reduction': '30,000', 'cost': '2,500,000', 'roi': '0', 'visual': 'New rail lines and stations', 'card image': 'II_9', },
{'name': 'Electric Vehicle (EV) Charging Stations', 'description': 'Install EV charging stations throughout the city. ROI comes from charging fees and increased EV adoption.', 'sector': 'Transport', 'emission reduction': '10,000', 'cost': '2,000,000', 'roi': '500,000', 'visual': 'Charging stations at various locations', 'card image': 'II_10', },
{'name': 'Dedicated Bus Lanes', 'description': 'Create dedicated lanes for buses to improve public transport efficiency.', 'sector': 'Transport', 'emission reduction': '15,000', 'cost': '1,000,000', 'roi': '0', 'visual': 'Bus lanes marked on major roads', 'card image': 'II_11', },
{'name': 'Park and Ride Facilities', 'description': 'Develop park and ride facilities to encourage public transport use. ROI comes from parking fees and increased public transport ridership.', 'sector': 'Transport', 'emission reduction': '10,000', 'cost': '1,000,000', 'roi': '100,000', 'visual': 'Parking areas near transit hubs', 'card image': 'II_12', },
{'name': 'Traffic Management Systems', 'description': 'Implement advanced traffic management systems to optimize vehicle flow.', 'sector': 'Transport', 'emission reduction': '25,000', 'cost': '1,500,000', 'roi': '0', 'visual': 'New traffic control centers', 'card image': 'II_13', },
{'name': 'Cycle Lanes Network', 'description': 'Develop an extensive network of cycle lanes to promote cycling.', 'sector': 'Transport', 'emission reduction': '15,000', 'cost': '1,000,000', 'roi': '0', 'visual': 'Cycle lanes marked on city roads', 'card image': 'II_14', },
{'name': 'Car-Free Zones', 'description': 'Create car-free zones in busy city areas to reduce emissions and promote pedestrian traffic.', 'sector': 'Transport', 'emission reduction': '50,000', 'cost': '500,000', 'roi': '0', 'visual': 'Car-free zones with pedestrian-friendly signage', 'card image': 'II_15', },
]

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
